### ISSUE TITLE
Embed HTML generated should be templatable

### ISSUE THREAD

**Issue by leewillis77** [leewillis77/wp-github-oembed#1]
Users should be able to copy a default template (From a selection?) into their theme and customise as required.

**Comment by xoroz** [comment]
I am sorry but for me it does not work.
I just insert the URL in my wordpress blog and nothing happened...
http://felipeferreira.net/index.php/nagios-plugins-github/
Am I missing something?

**Comment by leewillis77** [comment]
Hi @xoroz ;

It's working fine for me, see example here:

http://www.leewillis.co.uk/github-embed/

Make sure you've inserted the URL as plain text, not as a link...

**Comment by leewillis77** [comment]
PS. This issue relates to a specific feature. If you have further comments, can you open a fresh issue detailing your problem at https://github.com/leewillis77/wp-github-oembed/issues

**Comment by leewillis77** [comment]
Fixed by https://github.com/leewillis77/wp-github-oembed/pull/29
