### ISSUE TITLE
Custom CSS should be made possible

### ISSUE THREAD

**Issue by StephanBijzitter** [leewillis77/wp-github-oembed#12]
I got white text on a white background, not exactly a good thing:
![screenshot](http://puu.sh/eeKGl.png)

**Comment by StephanBijzitter** [comment]
I know that I can edit the CSS files, and that works, but not everyone knows how to do this. It would be a great improvement to usability to have this feature with a color picker.
![screenshot](http://puu.sh/eeLiV.png)

**Comment by leewillis77** [comment]
Hi, 

There's no need to edit the CSS in the plugin - everything should be overridable in your theme's CSS file. Since we specify a background colour, I'm tempted to also add a foreground colour by default, but I wouldn't add any "options" for this.
