### ISSUE TITLE
Does not work with WP4.1?

### ISSUE THREAD

**Issue by chrimm** [leewillis77/wp-github-oembed#13]
Hi there!

Sorry, but no matter how I try, I simply don't get this plugin to work with WordPress 4.1.
Is there any incompatibility? I can't see any. I tried to fix the oEmbed Regex, as I thought, the "." in ".com" needs to be escaped, but to no avail. I tried to change it to simple wildcard instead of regex – no avail yet.

There is no error message, no warning, nothing. It simply doesn't do anything. WordPress outputs the URL as it would have done without the plugin. And yes, I made sure that there is no link, just the URL. In a line of it's own. As you would do with any oEmbed URLs.

Any ideas? I'm helpless.
– Chris

**Comment by leewillis77** [comment]
Hi, 

I'm certainly not aware of any issues - I use it on my own blog which is still working fine, and I just tried it on a dev site running 4.1 without any problems. 

What's the URL you're trying to embed, maybe there's something odd coming in the response from GitHub for that repo?

**Comment by chrimm** [comment]
The URL was https://github.com/dd32/Github-to-WordPress-Plugins-Sync
I tried with http and https.

**Comment by leewillis77** [comment]
That works fine for me:

http://www.leewillis.co.uk/embed-test/

I guess there must be something else interfering - is your site in maintenance mode, or restricted in any other way?

**Comment by chrimm** [comment]
That's kind of weird. Nope, it's live and public: http://christoffertimm.de 
I'm using WordFence. Do you thing that may interfere? But well, as it's working at your site, I gonna go looking for the problem at my own.

Thank you for your help!

**Comment by leewillis77** [comment]
Hi - WordFence may well interfere - may be worth deactivating it temporarily? 

I'll close this for now, but of course if you find something, please do re-open!
