### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by lincolnthree** [leewillis77/wp-github-oembed#14]
I use the HTML editor, and I don't see a way to use this plugin? I tried "pasting" the link like usual, but I'm guessing there's probably some visual editor trick to use this? Documentation could be a little clearer on what "pasting" means.

I don't see how to use it at all. Is the URL supposed to be parsed out of the post automatically? If so, it's not working for me.

Any help or clarification would be much appreciated. Thanks!

**Comment by leewillis77** [comment]
Just paste it in :) See quick screencast here. 

https://dl.dropboxusercontent.com/u/9061517/wpembed.mov

Are you in maintenance mode or anything similar?

**Comment by lincolnthree** [comment]
Hmmm... just preview mode. I didn't try publishing. Should preview mode
work? Not in maintenance mode as far as I know.

On Thu, May 21, 2015 at 3:34 PM, Lee Willis <notifications@github.com>
wrote:

> Just paste it in :) See quick screencast here.
>
> https://dl.dropboxusercontent.com/u/9061517/wpembed.mov
>
> Are you in maintenance mode or anything similar?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/leewillis77/wp-github-oembed/issues/14#issuecomment-104396825>
> .
>



-- 
Lincoln Baxter, III
http://ocpsoft.org
"Simpler is better."

**Comment by lincolnthree** [comment]
I noticed that you used the visual editor. That's not an option for me,
unfortunately. Does this also work in the HTML source editor?

On Fri, May 22, 2015 at 11:14 AM, Lincoln Baxter, III <
lincolnbaxter@gmail.com> wrote:

> Hmmm... just preview mode. I didn't try publishing. Should preview mode
> work? Not in maintenance mode as far as I know.
>
> On Thu, May 21, 2015 at 3:34 PM, Lee Willis <notifications@github.com>
> wrote:
>
>> Just paste it in :) See quick screencast here.
>>
>> https://dl.dropboxusercontent.com/u/9061517/wpembed.mov
>>
>> Are you in maintenance mode or anything similar?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/leewillis77/wp-github-oembed/issues/14#issuecomment-104396825>
>> .
>>
>
>
>
> --
> Lincoln Baxter, III
> http://ocpsoft.org
> "Simpler is better."
>



-- 
Lincoln Baxter, III
http://ocpsoft.org
"Simpler is better."

**Comment by lincolnthree** [comment]
E.g. Is there a shortcode that can be used?

On Fri, May 22, 2015 at 11:15 AM, Lincoln Baxter, III <
lincolnbaxter@gmail.com> wrote:

> I noticed that you used the visual editor. That's not an option for me,
> unfortunately. Does this also work in the HTML source editor?
>
> On Fri, May 22, 2015 at 11:14 AM, Lincoln Baxter, III <
> lincolnbaxter@gmail.com> wrote:
>
>> Hmmm... just preview mode. I didn't try publishing. Should preview mode
>> work? Not in maintenance mode as far as I know.
>>
>> On Thu, May 21, 2015 at 3:34 PM, Lee Willis <notifications@github.com>
>> wrote:
>>
>>> Just paste it in :) See quick screencast here.
>>>
>>> https://dl.dropboxusercontent.com/u/9061517/wpembed.mov
>>>
>>> Are you in maintenance mode or anything similar?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/leewillis77/wp-github-oembed/issues/14#issuecomment-104396825>
>>> .
>>>
>>
>>
>>
>> --
>> Lincoln Baxter, III
>> http://ocpsoft.org
>> "Simpler is better."
>>
>
>
>
> --
> Lincoln Baxter, III
> http://ocpsoft.org
> "Simpler is better."
>



-- 
Lincoln Baxter, III
http://ocpsoft.org
"Simpler is better."

**Comment by leewillis77** [comment]
There's no shortcode - it works just fine in the HTML source editor for me. You might want to check your PHP error log and see if there's anything reported there.

**Comment by leewillis77** [comment]
I'm going to close this since there's been no further feedback and it WorksForMe.

**Comment by lincolnthree** [comment]
Sorry. I kinda gave up. Not sure what's going on here. Probably user error.
