### ISSUE TITLE
It's not working or I'm doing something stupid

### ISSUE THREAD

**Issue by morphx666** [leewillis77/wp-github-oembed#18]
First of all, thank for creating this plugin.

So, I just installed it and added a GitHub release link, but there's no release information being displayed... just the plain link.

You can see the link I added here: https://whenimbored.xfx.net/2012/10/x8086netemu-an-8086-emulator-in-vb-net/3/
It's near then end.

**Comment by f13dev** [comment]
Hi, When I first started using this plugin I had the same effect where a plain link was shown. If memory serves me correctly the issue was to do with the wordpress caching, for me clearing the plugins cache from the database resolved the issue.

**Comment by leewillis77** [comment]
Hi; 

There are two issues here:

1. "release" links aren't supported, the supported links are given on the main README, but for convenience are:
    * The main repo URL
    * Milestone URLs
    * Users
    * Repository contributors

2. You should be pasting the raw URL in, not linkiing it as text, e.g. 

https://www.dropbox.com/s/93b57ipzluidnd0/Screenshot%202017-03-10%2008.33.47.png?dl=0

**Comment by morphx666** [comment]
I did try the links suggested by the README and had the same results.
You can re-check the link I provided in the OP which now points to the main repository.

**Comment by leewillis77** [comment]
Please read my comments through:

Specifically:
> 2. You should be pasting the raw URL in, not linkiing it as text, e.g.
https://www.dropbox.com/s/93b57ipzluidnd0/Screenshot%202017-03-10%2008.33.47.png?dl=0

**Comment by morphx666** [comment]
Thanks! It is working perfect now.
Any chance you'll be adding release/releases links support?

**Comment by leewillis77** [comment]
I've no plans to add it, but I'd happily support a pull-request to add it.
