### ISSUE TITLE
Issu : My Repository don't show up

### ISSUE THREAD

**Issue by felakkad** [leewillis77/wp-github-oembed#19]
You Plugin is perfect for my need.

I am adding to a git file all my chrome pages with a chrome extension.

https://github.com/felakkad/Page_To_Read/blob/master/Link_To_Read

And i would like to publish this content to a Wordpress post, but seems to doesnt work.

My blog and post : http://vroomblog.com/link-test/

I tried with file and repo no thing show.

Did I do something wrong ?

Thanks

**Comment by leewillis77** [comment]
You've placed a link to the repo in your post - you should just have the URL as plain text, not as a link.

**Comment by felakkad** [comment]
I create it on page and remove the link and put it as plain text.

http://vroomblog.com/vlink-it-grabber/

Still doesnt work, there is a way to force it ?

Thanks

**Comment by leewillis77** [comment]
Hi; 

It's working fine for me here:

![screenshot 2017-07-20 14 26 44](https://user-images.githubusercontent.com/1097338/28419628-81cb6374-6d57-11e7-8317-79a6a163e6f5.png)

It looks like you may have some spaces in there before the URL? WordPress will only try an embed if the URL is the **only** thing on that line:

![screenshot 2017-07-20 14 27 55](https://user-images.githubusercontent.com/1097338/28419661-a35280fe-6d57-11e7-9597-1aca1e3b7a4b.png)

**Comment by felakkad** [comment]
You are amazing, now is working !!!!! 

https://wordpress.org/plugins/github-embed/

Thanks a lot for your work

**Comment by leewillis77** [comment]
You're welcome :)
