### ISSUE TITLE
Doesnt work anymore

### ISSUE THREAD

**Issue by swwwolf** [leewillis77/wp-github-oembed#20]
Hello,

I'm using this plugin for years, thank you so much. Not a long time ago I'm noticed that it is broken, but can't remember an exact time. Looks like the plugin skipping the link, see here: https://sww-it.ru/projects

Please take a look.

**Comment by leewillis77** [comment]
Hi;

It's still working fine for me, I just embedded the repo you mentioned just fine:

https://www.dropbox.com/s/7fkboa02s2hrfz6/Screenshot%202017-07-28%2009.15.10.png?dl=0

The two most likely causes are:

1. The URL isn't on a line on its own
2. There's another plugin / custom code conflicting

If you can reproduce this on a site with a base theme installed, and no other plugins then I'd be happy to take a look but at this stage it looks like something specific to your site.

**Comment by swwwolf** [comment]
It could be conflicting problem. The URL is on a line of its own, but surrounded by <p>. I've also checked with default theme and by disabling some of the plugins, but with no success.

Is it possible to enable some kind of tracing for the plugin?

**Comment by leewillis77** [comment]
You can add the following to your wp-config.php:

```
define('GITHUB_API_LEVEL', 2);
```

That should result in API interactions being dumped to your error log. However I doubt you'll actually see anything. Since I can embed the URL I don't think the issue is there. The most likely issue is that something is causing WordPress core to not even try to embed the URL.

**Comment by swwwolf** [comment]
Thanks, it didn't help. Looks like there is some conflict, but I have no idea what kind of, because nor disabling plugins, nor using default theme helps at all. Also, I've checked on a different site and it works. So, closing the issue for now. Thanks!
