### ISSUE TITLE
Great!Thanks for your share

### ISSUE THREAD

**Issue by jilaokang** [leewillis77/wp-github-oembed#21]
I am a new hand，don't konw how to use it , Can you give me a example?
Thank you！

**Comment by jilaokang** [comment]
I put the url in pages but no display.

**Comment by leewillis77** [comment]
The plugin is still working just fine for me. 

Can you give me an example of:
1. The GitHub URL that you are pasting into your content
2. The page where you've tried to embed it

**Comment by jilaokang** [comment]
http://volcan.top/index.php/2017/10/31/wordpressblog/ look like this page.

**Comment by jilaokang** [comment]
The plugin has been started

**Comment by leewillis77** [comment]
It's still working fine for me, I just embedded the user you mentioned just fine:

https://www.leewillis.co.uk/github-embed/

The two most likely causes are:
- The URL isn't on a line on its own
- There's another plugin / custom code conflicting

**Comment by jilaokang** [comment]
Thank you for your sunny answer. I try，but not fine，Can you login to make it solve it ? 

LoginURL:http://volcan.top/wp-login.php
user:516764216@qq.com
password:747697qqmm

**Comment by jilaokang** [comment]
Thank you for your sunny answer. I try，but not fine，Can you login to  solve it ?

LoginURL:http://volcan.top/wp-login.php
user:516764216@qq.com
password:747697qqmm

**Comment by jilaokang** [comment]
I have changed language to English

**Comment by leewillis77** [comment]
This is a public site. Do NOT post login credentials here. I'd advise you to remove that user login / password immediately.

**Comment by leewillis77** [comment]
I don't provide any formal support for my free plugins. The plugin is working for me, and passing all tests, so if there's an issue it's either down to the URL not being pasted in correctly, or another plugin / custom code conflicting. I can't offer any support for resolving those I'm afraid.

**Comment by jilaokang** [comment]
Thank for your advise， it's my apology.

 Your portrait is very handsome

**Comment by leewillis77** [comment]
Closed. Works for me.
