### ISSUE TITLE
Allow to embed pull requests as well

### ISSUE THREAD

**Issue by lucamauri** [leewillis77/wp-github-oembed#22]
Plugin should be able to decode link to Pull request and create a box from it.
For instance a link like `https://github.com/Inclumedia/RecentPages/pull/4` should result in a box like the one already generated for _Milestones_ for instance.

**Comment by leewillis77** [comment]
Hi; 

Thanks for opening the issue. Pull-requests are often time sensitive - ie they're only really relevant between the time they're open and the time they're closed. I'm not sure why you'd want to embed them in a blog post. 

That said, I'm open to someone submitting a pull-request for this which I'd definitely consider adding.

**Comment by lucamauri** [comment]
I understand you meaning: if you contribute to a project and you want to show what your contribution was and when it was merged, if ever, then a link to the pull request is the easiest way in my opinion.

I am working on this addition as it seems I can manage it by reusing lot of code. But please note this is the first time I work with WP extension, so I kindly ask you to help.
After I added the proper code, how can I test this before submitting as a pull request?
Sorry for the very basic question and thanks for the help.

**Comment by leewillis77** [comment]
> After I added the proper code, how can I test this before submitting as a pull request?

Just install it on one of your own sites / local development machine and check that you can embed everything that is currently supported. There aren't any formal unit tests or similar at the moment.

**Comment by leewillis77** [comment]
No progress. Feel free to re-open once you have a PR ready.
