### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by giacomocerquone** [leewillis77/wp-github-oembed#23]
Hi, I downloaded, installed and enabled this plugin on [italiancoders](http://italiancoders.it) but nothing shows-up.
What can I check to understand the cause of the problem? Could be the theme that is blocking the plugin?

Wp version: 4.9.1

**Comment by leewillis77** [comment]
Can you provide a URL to the page that you're trying to embed something on, and the URL that you're trying to embed.

**Comment by giacomocerquone** [comment]
Wooa this was quick :smile: 

Post link: https://italiancoders.it/routing-delle-applicazioni-angular/
Github repo link: https://github.com/giacomocerquone/angular-routing.git

In the mean time I was looking at your preg_match, I'm about to try to link the issues section in order to see what happens

**Comment by leewillis77** [comment]
The GitHub repo link shouldn't have `.git` on the end, it should just be:

`https://github.com/giacomocerquone/angular-routing`

That embeds just fine for me, see:
https://www.leewillis.co.uk/github-embed/

**Comment by giacomocerquone** [comment]
Changed, still doesn't work

**Comment by leewillis77** [comment]
I can't see the URL anywhere on https://italiancoders.it/routing-delle-applicazioni-angular/ ?

**Comment by giacomocerquone** [comment]
At "Tutto il codice di questo articolo potete trovarlo sulla relativa repo del mio profilo di github: [angular-routing](https://github.com/giacomocerquone/angular-routing)"

**Comment by leewillis77** [comment]
That's a link to the repo with specific text - the plugin won't touch that. 

What you should have is the URL you want to embed in your content on a line by itself, e.g.

![screenshot 2017-12-12 15 44 05](https://user-images.githubusercontent.com/1097338/33893447-55195110-df53-11e7-83a8-9b99507a1e0c.png)

**Comment by giacomocerquone** [comment]
I tried that too. Anyway we have the website down right now, as soon as it comes back online I'll try this.

Thank you very much for now!

**Comment by giacomocerquone** [comment]
Spectacular, it works now! Thanks
