### ISSUE TITLE
Display more then 1 mileston

### ISSUE THREAD

**Issue by dreamfoxmedia** [leewillis77/wp-github-oembed#26]
Is it possible to display more then 1 milestone?

**Comment by leewillis77** [comment]
Hi; 

You can add multiple milestone URLs to your pages / posts, e.g. 

```
https://github.com/php-censor/php-censor/milestone/2
https://github.com/php-censor/php-censor/milestone/1
```

Is that what you mean?

**Comment by dreamfoxmedia** [comment]
Kinda. then i have to manually edit the milestones everytime i add a new one or 1 is due date.

**Comment by dreamfoxmedia** [comment]
Its not possible to shoa all upcomming milestones automatiicly?

**Comment by leewillis77** [comment]
Not currently, no.
