### ISSUE TITLE
Github Logo out of date

### ISSUE THREAD

**Issue by cass-e-design** [leewillis77/wp-github-oembed#28]
the Github logo referenced is out of date, coming from the [media](https://github.com/github/media) repository. From their readme:

> NOTE: This repository is no longer supported or updated by GitHub. Please check out our official Logos page to find official GitHub logos as well as our beloved Octocat, along with guidelines for how you can use them.

I'd get if you didn't want to upload a copy of the mark inside the plugin though, and I don't know if they're hosted elsewhere for easy referencing anymore.

edit: wanted to add that I love the plugin, just thought you might want to know
double edit: just saw the pr someone had to add svg support, sorry

**Comment by leewillis77** [comment]
Fixed. Thanks!
