### ISSUE TITLE
[GitHub API] Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by CodyMcMichael** [leewillis77/wp-github-oembed#32]
Hey, we are using your plugin on one of our sites and we received this email from Github. Is this something you are planning on addressing  or working on? Thanks a bunch!

__________________

Hello there!

On February 3rd, 2020 at 22:15 (UTC) your application used its `client_id` and `client_secret` (with the User-Agent WordPress Github oEmbed plugin)

Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.

**Comment by leewillis77** [comment]
v2.0 supports authenticating with [Personal Access Tokens](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line):

```php
add_filter( 'github-embed-access-token', function ( $v ) {
	return 'INSERTYOURPERSONALACCESSTOKENHERE';
} );
add_filter( 'github-embed-access-token-username', function ( $v ) {
	return 'INSERTYOURUSERNAMEHERE';
} );
```
