### ISSUE TITLE
Repo contributors link enlarges contributors using the default GitHub avatar

### ISSUE THREAD

**Issue by funbeedev** [leewillis77/wp-github-oembed#34]
When using the link for a GitHub repos contributors page, any contributor using the default GitHub profile avatar is unusually enlarged.

See image below showing a page on my site using the link to a GitHub repo contributors. As you can see, only contributors that are not using the default GitHub profile avatar are sized okay.

![image](https://user-images.githubusercontent.com/66768334/107131219-6b6f3780-68cc-11eb-98d6-34c7b4a4c0c2.png)

**Comment by leewillis77** [comment]
Thanks for the report. This is fixed in v2.0.2.

**Comment by funbeedev** [comment]
Thanks for fixing this quickly :)
